### ISSUE TITLE
1.4.7 handler 

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupportBungee#11]
The PS Bungee doesn't support the newly added 1.4.7 support. This one is easy if I remember correctly, back from when I added it to Sky Islands servernetwork

**Comment by Shevchik** [comment]
Don't have time for that, but yea changing a few lines should be enough.

**Comment by Tom-III** [comment]
I don't think it needs a separate handler, I think it can use the 1.5.2 one without issues

**Comment by Shevchik** [comment]
Inventory open packet is different in 1.4.7

**Comment by Tom-III** [comment]
Isn't that handled in ProtocolSupport and not in bungee?

**Comment by Shevchik** [comment]
It is, but on bungee you still need to decode/encdoe packets because you still needs to handle chat and other packets bungee side.

**Comment by Tom-III** [comment]
If I add this, will you add it to main code?

**Comment by JunkyBulgaria** [comment]
@Tom-III try this https://github.com/JunkyBulgaria/ProtocolSupportBungee not sure if there would be any bugs

**Comment by Tom-III** [comment]
Awesome, could you fix 1.9 support cause I couldn't get it working?

**Comment by JunkyBulgaria** [comment]
actually as @Shevchik said it is not implemented properly, there's chat and inventory packets that haven't been implemented yet and might crash the game, about the 1.9 i'll see what i can do
