### ISSUE TITLE
Add support to 1.7.*

### ISSUE THREAD

**Issue by TiTo-418** [ProtocolSupport/ProtocolSupportBungee#17]
It doesn't work

![screenshot_24](https://cloud.githubusercontent.com/assets/11008016/14230856/319a3be0-f941-11e5-930c-39db9ea7edb4.png)

**Comment by GabrielAugustoTI** [comment]
Why closed? NOT FIXED YET!

**Comment by Shevchik** [comment]
This plugin development is closed, find yourself a 1.7-1.10 bungee.
