### ISSUE TITLE
1.6.4 & 1.6.1 support not working

### ISSUE THREAD

**Issue by Games4k** [ProtocolSupport/ProtocolSupportBungee#38]
_The latest master build is not working on 1.6.4 & 1.6.1_
(Tested on Bungeecord 1.12 & Travertine 1.12), not tested on Bungee 1.12.1

![capture](https://user-images.githubusercontent.com/29690431/30493494-943a3656-9a44-11e7-8fb4-c8e4d0c3049d.PNG)

**Comment by Games4k** [comment]
Edit: Tested on BungeeCord & WaterFall 1.12.1, but still nothing ;)

**Comment by krusic22** [comment]
If you need it like right now and no time to wait use: https://github.com/ridalarry/ProtocolSupportBungee
Or just wait for the official version...

**Comment by Games4k** [comment]
@krusic22 Thanks ;)
This is not very important plugin for me, but still, I wanted to report this :D

**Comment by Games4k** [comment]
Also, its not working too :O

**Comment by krusic22** [comment]
Works for me... 
Plugins maybe? Or Online mode stuff?

**Comment by Games4k** [comment]
When you try to connect join with 1.6.4...
https://user-images.githubusercontent.com/29690431/30493494-943a3656-9a44-11e7-8fb4-c8e4d0c3049d.PNG
and the join button is not clickable

**Comment by krusic22** [comment]
Direct connect?

**Comment by Games4k** [comment]
This is just my test bungeecord, without any plugins or anything else. Version 1.12.1...
![capture](https://user-images.githubusercontent.com/29690431/30494020-c99abdc8-9a46-11e7-9433-60c76337da22.PNG)

**Comment by krusic22** [comment]
Does bungee give and error?

**Comment by Games4k** [comment]
Nop

**Comment by Games4k** [comment]
Its working now with directconnect (I was banned on lobby so it gives me screen above), but still... No one is using directconnect xD

**Comment by krusic22** [comment]
That's good. So it just sends the wrong version to the client...

**Comment by Games4k** [comment]
Also, can you tell me your spigot name, I want to ask you something...

**Comment by krusic22** [comment]
I have the same username everywhere.

**Comment by krusic22** [comment]
Tested it... Always reports 1.3 probably because its not ready for prime time yet.
![untitled](https://user-images.githubusercontent.com/8352435/30494568-04838d96-9a49-11e7-8c35-3c8bc58663ed.png)

**Comment by gdude2002** [comment]
PSBungee is simply not ready yet. I'm not sure what you guys are up to here, but there are no releases of it, and it certainly isn't very functional just yet.

**Comment by Games4k** [comment]
There are GitHub commits. Its possible to compile it and get version that is "updated" 18 days ago
![capture](https://user-images.githubusercontent.com/29690431/30516045-28e9d406-9b34-11e7-9cd7-9e5551f2df7a.PNG)

**Comment by gdude2002** [comment]
Kind of getting ahead of yourselves. Perhaps wait for a working release?
