### ISSUE TITLE
Error for 1.6.4 Support

### ISSUE THREAD

**Issue by Stualyttle** [ProtocolSupport/ProtocolSupportBungee#40]
Heye, I've tried using the plugin in my bungee,
1.6 is loading, but if i try to join it says, bad login. am i doing something wrong??
![image](https://user-images.githubusercontent.com/27898452/30967010-24464940-a45b-11e7-8fc0-17c1d53d13d4.png)
No error in console when i join, just a connection, no error, and no disconection..
Sorry for my english, i'm dutch :P 
Thank you for reading :D 
Bye

**Comment by Shevchik** [comment]
You have online mode enabled, but the client doesn't use it.

**Comment by Stualyttle** [comment]
And What do i need to chanse than? (and not allowing crached clients)

**Comment by Shevchik** [comment]
Make sure that your client is actually using online mode

**Comment by 7kasper** [comment]
^ It seems like you are using the technic launcher or something
Try it without.
