### ISSUE TITLE
The motd of the server didn't show when i used the lastest version of PSBungee and BuneeCord.

### ISSUE THREAD

**Issue by Singlerr** [ProtocolSupport/ProtocolSupportBungee#45]
When i refreshed the server list of minecraft,my server showed 'Can't reach the server' in the server list.I used the latest version of this plugin and bungeecord from Jenkins.

**Comment by Icey-girl** [comment]
@Singlerr  You need the latest hexa cord

**Comment by Singlerr** [comment]
@icey-girl I already  used it.But still not working.

**Comment by MrPowerGamerBR** [comment]
Can confirm, the server MOTD doesn't work with 1.5.2 (and probably any other version that uses the pre 1.6 (?) protocol ping)

Connecting does work

**Comment by MrPowerGamerBR** [comment]
Can confirm that this also happens with 1.6.X

![https://mrpowergamerbr.com/uploads/javaw_2018-02-12_21-17-53.png](https://mrpowergamerbr.com/uploads/javaw_2018-02-12_21-17-53.png)

**Comment by Singlerr** [comment]
@MrPowerGamerBR
So can i make this plugin show motd in 1.5.2 if i edit the source of this plugin?

**Comment by MrPowerGamerBR** [comment]
@Singlerr no, we (me and Shevchik) were trying to debug why this was happening in ProtocolSupport's Discord server, I think it is PSBungee adding stuff that shouldn't be there, causing the MOTD not to work in 1.6.

**Comment by MrPowerGamerBR** [comment]
Fixed MOTD for 1.6.X clients

![https://mrpowergamerbr.com/uploads/javaw_2018-02-13_11-44-14.png](https://mrpowergamerbr.com/uploads/javaw_2018-02-13_11-44-14.png)

1.5.X and 1.4.X are still broken, soon:tm:

**Comment by Singlerr** [comment]
@MrPowerGamerBR Thanks! I solved a lot of question by your comment!

**Comment by Singlerr** [comment]
@MrPowerGamerBR Good job!

**Comment by BBoyJD10** [comment]
Not working in 1.13 snapshots

**Comment by MrPowerGamerBR** [comment]
@BBoyJD10 I guess that's a HexaCord issue not a ProtocolSupportBungee issue... is HexaCord even updated for 1.13?

**Comment by BBoyJD10** [comment]
It doesnt work on 1.6 it says bad loginthough

**Comment by MrPowerGamerBR** [comment]
@BBoyJD10 Then that's an unrelated issue, ProtocolSupportBungee works fine for me on a Paper 1.12.2 server + HexaCord.

Also, as far as I know Mojang fucked up the session ID for 1.6.X clients in the new launcher, so the client will only connect if HexaCord is in offline mode.

**Comment by MrPowerGamerBR** [comment]
@BBoyJD10 Unless if you cannot reproduce this issue with only ProtocolSupport, then yeah, it is a bug.

If that's the case, please open a new issue! 👋
