### ISSUE TITLE
1.4.7 and 1.5.2 don't view server online

### ISSUE THREAD

**Issue by mchiappinam** [ProtocolSupport/ProtocolSupportBungee#46]
The server is functional, all ok, but in the server list it shows as if you were Offline. This is only happening with BungeeCord. I tried different versions and the one of the HexagonMC also, but I did not obtain success.

**Comment by MrPowerGamerBR** [comment]
This is a duplicate issue: https://github.com/ProtocolSupport/ProtocolSupportBungee/issues/45
