### ISSUE TITLE
[BUG?] PE client cannot switch server on bungeecord

### ISSUE THREAD

**Issue by Mayomi** [ProtocolSupport/ProtocolSupportBungee#47]
after send player from lobby1 to lobby2. The server can see the player join but client cannot get any data from server(like fall void)

**Comment by 7kasper** [comment]
Probably due to pluginmessages not yet being supported. Shev is working on it.

**Comment by caoli5288** [comment]
The respawn packet from server to client not impl yet. I try to impl it follow spigot side protocolsupport but it not works. 

Any project member can help me? @7kasper

**Comment by Shevchik** [comment]
You won't be able to implement the dimesnion switch (respawn) the same way as it is implemented on server side. Also due to problems with mcpe not being able to handle dimension switch too fast, we have to add additional workarounds to server.

**Comment by caoli5288** [comment]
@Shevchik [Nemisys](https://github.com/iTXTech/Nemisys) is a multiserver proxy for mcpe. I see it open new server conn, redirect client directly(not like bungeecord pre-process conn) and send a cached login packet(id 1) while do server switch. it switch server quick just like bungeecord.

Maybe we need modify bungeecord's code?

**Comment by caoli5288** [comment]
@Shevchik Anything I can do? I'm not very familiar with the PE protocol but Familiar with Java

**Comment by Outfit8TSB** [comment]
You should use GeyserMC and ViaVersion Instead.
I will make sure the legacy version addon for ViaVer
