### ISSUE TITLE
New errors on latest version

### ISSUE THREAD

**Issue by BBoyJD10** [ProtocolSupport/ProtocolSupportBungee#50]
15.02 09:17:04 [Server] SEVERE Feb 15, 2018 9:17:04 AM protocolsupport.utils.netty.ChannelInitializer exceptionCaught
15.02 09:17:04 [Server] INFO WARNING: Failed to initialize a channel. Closing: [id: 0x285061f3]
15.02 09:17:04 [Server] INFO java.lang.IllegalArgumentException: handler
15.02 09:17:04 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
15.02 09:17:04 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.setHandler(HandlerBoss.java:33)
15.02 09:17:04 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.setHandler(BungeeNettyChannelInjector.java:108)
15.02 09:17:04 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.<init>(BungeeNettyChannelInjector.java:102)

15.02 09:17:03 [Server] INFO WARNING: Failed to initialize a channel. Closing: [id: 0xfa501714]
15.02 09:17:03 [Server] INFO java.lang.IllegalArgumentException: handler
15.02 09:17:03 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
15.02 09:17:03 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.setHandler(HandlerBoss.java:33)
15.02 09:17:03 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.setHandler(BungeeNettyChannelInjector.java:108)
15.02 09:17:03 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.<init>(BungeeNettyChannelInjector.java:102)
15.02 09:17:03 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$ChannelInitializerEntryPoint.initChannel(BungeeNettyChannelInjector.java:52)
15.02 09:17:03 [Server] INFO at protocolsupport.utils.netty.ChannelInitializer.channelRegistered(ChannelInitializer.java:17)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128)
15.02 09:17:03 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1332)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
15.02 09:17:03 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:829)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
15.02 09:17:03 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
15.02 09:17:03 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
15.02 09:17:03 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
15.02 09:17:03 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
15.02 09:17:03 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

**Comment by MrPowerGamerBR** [comment]
1. What plugins are you using?
2. What HexaCord version are you using?
3. What client version did you test?

**Comment by BBoyJD10** [comment]
Only protocolsupportbungee, latest version, 1.12.2

**Comment by MrPowerGamerBR** [comment]
Are you using online or offline mode?

I tested on my server with HexaCord (offline mode) + 1.12.2 client + ProtocolSupportBungee and it worked without any issues

**Comment by MrPowerGamerBR** [comment]
Are you using the latest ProtocolSupportBungee development build? The version on SpigotMC is outdated

**Comment by BBoyJD10** [comment]
Yes latest dev build and causing issues on large 150 player plus servers

**Comment by MrPowerGamerBR** [comment]
@BBoyJD10 can you figure out when this happens? (example: on login, server switch, etc)

Also, I think ProtocolSupport itself doesn't change the connection of any version that isn't 1.4.X/1.5.X/1.6.X, so if it is happening with 1.12.2 players then it is very strange...

**Comment by BBoyJD10** [comment]
On login and causes chat to become incredibly slow

18.02 14:49:15 [Server] SEVERE Feb 18, 2018 2:49:15 PM protocolsupport.utils.netty.ChannelInitializer exceptionCaught
18.02 14:49:15 [Server] INFO WARNING: Failed to initialize a channel. Closing: [id: 0x349646c9]
18.02 14:49:15 [Server] INFO java.lang.IllegalArgumentException: handler
18.02 14:49:15 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
18.02 14:49:15 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.setHandler(HandlerBoss.java:33)
18.02 14:49:15 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.setHandler(BungeeNettyChannelInjector.java:108)
18.02 14:49:15 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.<init>(BungeeNettyChannelInjector.java:102)
18.02 14:49:15 [Server] INFO at protocolsupport.injector.BungeeNettyChannelInjector$ChannelInitializerEntryPoint.initChannel(BungeeNettyChannelInjector.java:52)
18.02 14:49:15 [Server] INFO at protocolsupport.utils.netty.ChannelInitializer.channelRegistered(ChannelInitializer.java:17)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128)
18.02 14:49:15 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1332)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
18.02 14:49:15 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:829)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
18.02 14:49:15 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
18.02 14:49:15 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
18.02 14:49:15 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
18.02 14:49:15 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
18.02 14:49:15 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

**Comment by ExenalEurope** [comment]
Same problem here, https://hastebin.com/ecopihoyax.sql
latest jenkins

**Comment by Shevchik** [comment]
BungeeCord can now close connection before even initializing the pipeline. We shouldn't try to init in this case.

**Comment by ExenalEurope** [comment]
Seems to be only occurring on the newest versions of Bungeecord.

**Comment by ExenalEurope** [comment]
I'm not an expert so I don't know how to fix this issue, hopefully, it will be fixed very soon, it is not allowing me to test ProtocolSupportBungee

**Comment by ExenalEurope** [comment]
I checked and BungeeCord-Bootstrap:1.13-SNAPSHOT:9a2acc8:**1390** works.
