### ISSUE TITLE
Cannot connect to server.

### ISSUE THREAD

**Issue by Zilacon** [ProtocolSupport/ProtocolSupportBungee#51]
We are trying to connect to our HUB using PSB and Hexacord.
PSB is latest jenkins build. Hexacord is v184 (latest). Our hub is Spigot b1608 1.12.2 (March 7th, Latest)
Connecting to HUB using 1.12.2 is fine.
Connecting to HUB using 1.7.10 is fine.
Connecting to HUB using 1.6.4 throws a UUID error.
Connecting to HUB using 1.5.2 throws a UUID error.
Connecting to HUB using 1.4.7 throws a UUID error.

Hub is default. Connection throttle set to -1, online mode set to false. Everything else is pretty much out of the box spigot. The HUB does have the latest version of ProtocolSupport in the plugins.

I am guessing the UUID problem has something to do with mojangs recent decision of removing legacy support. So things like skins from versions before 1.7.10 just show as steve, as these servers are grabbing the username and not the uuid, so mojang ignores them now. Not sure if its related, just an observation.

The testing was done by TheresaJayne, She will be providing the screenshots and logs below. We worked together to get a test environment working on her end as i already have a bungeecord network running on my own network and did not want them to conflict.

**Comment by theresajayne** [comment]
[error.log](https://github.com/ProtocolSupport/ProtocolSupportBungee/files/1792509/error.log)
![164error](https://user-images.githubusercontent.com/832515/37143348-c8af71e8-22b2-11e8-953b-26448100d8df.PNG)

**Comment by Shevchik** [comment]
Are you sure that you are using bungeecord alt-respawn branch?

**Comment by Zilacon** [comment]
I am not sure what that is, could you explain?

**Comment by Zilacon** [comment]
This is the bungeecord we are using: https://github.com/HexagonMC/BungeeCord/releases/tag/v184

**Comment by theresajayne** [comment]
The UUID error is in the error.log 
08:57:43 [SEVERE] [theresajayne] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(10) + length(8) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 10, widx: 14, cap: 14)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403)
    at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812)
    at net.md_5.bungee.protocol.DefinedPacket.**readUUID**(DefinedPacket.java:214)

**Comment by Shevchik** [comment]
Right now it only works with https://github.com/SpigotMC/BungeeCord/tree/alt-respawn.
Hexacord doesn't have a branch that does the same.

**Comment by Zilacon** [comment]
Does that version have support for 1.7.10? We were hoping to have support for 1.5.2, 1.6.4, 1.7.10, and 1.12.2. And have a single vanilla server to act as the hub running 1.12.2 using ProtocolSupport.

**Comment by Shevchik** [comment]
No it doesn't. You will have to either use psb pre alt-respawn build, or port alt-respawn to hexacord, or wait until psb supports 1.7.10 natively.

**Comment by theresajayne** [comment]
what is the key differences for alt-respawn that allows it to work? can you point at some of the files i need to transfer or is it generic across the board changes?

**Comment by theresajayne** [comment]
Just compiled up the alt-respawn and its the same error

**Comment by Shevchik** [comment]
Well, then i need a full log to find out which exact packet causes this error.
Anyway the alt-respawn branch as only 1 commit that you need to apply.

**Comment by theresajayne** [comment]
ok how do i get the full log for you?

**Comment by Zilacon** [comment]
Pretty sure the packet id was 145.

**Comment by theresajayne** [comment]
Error.log attached that is the output from bungee(alt_respawn) when trying to connect with vanilla 1.5.2
Latest.log is the same attempts but as seen from the vanilla 1.12.2 server
There are no logs available on the vanilla client.
[latest.log](https://github.com/ProtocolSupport/ProtocolSupportBungee/files/1792857/latest.log)
[error.log](https://github.com/ProtocolSupport/ProtocolSupportBungee/files/1792854/error.log)

**Comment by Shevchik** [comment]
Yeah, the provided exception issues is caused by EntityMap packet rewriter which sohuldn't be present in alt-respawn branch. Are you sure that you used the alt-respawn compiled branch jar?

**Comment by theresajayne** [comment]
I pulled from github and compiled, let me recheck

**Comment by theresajayne** [comment]
Ok applied the changes to hexacord and now we can connect with 1.6.4 and below to the vanilla 1.12.2 lobby, but on trying to connect to the actual server we get 
2018-03-08 11:43:46 [INFO] [Minecraft-Client] [CHAT] Exception Connecting:NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

**Comment by Zilacon** [comment]
When connecting to the 1.6.4 server from the 1.12.2 HUB it says Disconnecting IP: Protocol Error.
But it doesn't say that when directly connecting to the IP:PORT bypassing bungee.

Any ideas?

**Comment by Shevchik** [comment]
Are you sure that your backed server has encapsulation protocol implementation (i.e. has ProtocolSupport installed, or you have implemented it yourself)?

**Comment by Zilacon** [comment]
PSB is installed on the bungee, and PS is installed on the 1.12.2 Spigot server acting as the hub. But no PS is used on the 1.6.4 server as you do not support any versions lower than 1.12.2.

**Comment by theresajayne** [comment]
ProtocolSupport.jar is in the plugins folder, and showing on 1.12.2 but its of course not in the 1.6.4 server

**Comment by Shevchik** [comment]
Then you need to implement encapsulation protocol yourself (see psb readme).

**Comment by theresajayne** [comment]
So you are saying that we cannot get ProtocolSupport for 1.6.4 and have to manually support it ourselves? 
Are there any examples and does this need to be done as a bukkit plugin or do we have to modify ancient versions of MCPC+?

**Comment by Shevchik** [comment]
You need to inject your own handlers into player network on the server. It is possible to do via plugin, just make sure that your are using mcp field for reflection, or direct nms.

**Comment by theresajayne** [comment]
Are there any examples of exactly what is needed? I have read the link provided but it means nothing at all to me as I am not familiar with whats needed to be changed? an example plugin framework would be helpful to allow people like me to learn what is needed.

**Comment by Shevchik** [comment]
Are you familiar with how network works in 1.6.4? (and all pre netty versions). You basically need to rewrite the 1.6.4 network to use the described protocol (it resembles mojang current protocol).

**Comment by Shevchik** [comment]
There isn't a small example for that unfortunately. You will have to start with how network works in current and in new versions.

**Comment by Zilacon** [comment]
@Shevchik could you possibly make a torn down version of protocolsupport with JUST the networking code that is needed for clients to connect with PSB on bungee for 1.12.2? And we can possibly work from there since we have a example to work from.

**Comment by Shevchik** [comment]
You won't be able to apply it to cauldron anyway, because it doesn't have netty. Post here version of cauldron you use, will try to create a simple plugin that overrides network.

**Comment by Zilacon** [comment]
We dont use cauldron, we use thermos for 1.7.10. And MCPC+ for 1.5.2, 1.6.4.
Specifically these versions:
https://yivesmirror.com/grab/mcpc/mcpc-plus-1.5.2-R1.1-forge738-B653.jar
https://yivesmirror.com/grab/mcpc/mcpc-plus-1.6.4-R2.1-forge965-B243.jar
https://yivesmirror.com/grab/thermos/Thermos-1.7.10-1614-56.zip

Version 57 of thermos has known issues with many mods that was never fixed, so were still on 56.
Also note for 1.5.2 and 1.6.4 we use TickThreading which ill link below, but ive asked Nallar if your plugin would conflict with his wrapper and he said no. But i figured id mention it either way.
https://github.com/MinimallyCorrect/TickThreading/tree/1.5.2
https://github.com/MinimallyCorrect/TickThreading/tree/1.6.4

**Comment by Zilacon** [comment]
Im heading to bed now, let me know if you need anymore information.
Thanks.

**Comment by Zilacon** [comment]
@Shevchik Hows it going?

**Comment by Zilacon** [comment]
@Shevchik Any progress so far? Im kinda excited to get this setup working :)

**Comment by Shevchik** [comment]
I started working on that, but i'm currently busy with other things, so it will take time.

**Comment by Zilacon** [comment]
Ok, thanks for replying. Keep me up to date if you could.
Thank you for going out of your way to fix this for us.

**Comment by Zilacon** [comment]
Could you give us a time frame of when this could be done please?

**Comment by Shevchik** [comment]
Something between 1 day and never.

**Comment by Zilacon** [comment]
Well i hope its not never. Looking forward to having everything on one network.

**Comment by Zilacon** [comment]
Right as well close this since we got someone to actually make bungeecord support 1.4.7-1.14.4 properly within itself.

And also you never even bothered to solve the problem in the first place.
