### ISSUE TITLE
Too big packet loss

### ISSUE THREAD

**Issue by caoli5288** [ProtocolSupport/ProtocolSupportBungee#52]
![qq 20180312210956](https://user-images.githubusercontent.com/3120587/37285472-09d43a52-263a-11e8-9f19-38190f3a7efe.png)

In 40Gib bound private network.

**Comment by Shevchik** [comment]
Wrong repo. This issue belongs to RakNetServer. But anyway, RakNetServer only allows 256 packets to be lost.

**Comment by caoli5288** [comment]
@Shevchik Most player cannot join server while this exception detected except.
restart bungeecord can fix but hope auto re-health.
How can I do for this issue?

**Comment by Shevchik** [comment]
Fix your network, or increase the packet loss limit in raknetserver library.

**Comment by caoli5288** [comment]
@Shevchik It's 4x10GiB fiber network. It's should not be network's issue.
Is it ownstream server lag caused?
