### ISSUE TITLE
Is pe supported right now?

### ISSUE THREAD

**Issue by gabe56f** [ProtocolSupport/ProtocolSupportBungee#62]
While the readme clearly includes the "pe clients" part, i can't really get it to work. I have the mcpenew branch on the server, but the pe client doesn't seem to find the server.

Using latest HexaCord, latest dev build of ProtocolSupportBungee, and finally the latest mcpenew. I just rebuilt it.

**Comment by Shevchik** [comment]
It is hidden behind the system propertly. Inspect the source to find out it's name.
