### ISSUE TITLE
Bump PE version

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupportBungee#66]
As above, connecting with PE throws Outdated Server info.

**Comment by Princess-of-Klaxosaurs** [comment]
Nope why Shult they

**Comment by Princess-of-Klaxosaurs** [comment]
Mrpowergamer is doing other things probably

**Comment by MrPowerGamerBR** [comment]
Is ProtocolSupportBungee disconnecting, or is ProtocolSupport?

**Comment by MrPowerGamerBR** [comment]
I did try update PSBungee a few weeks ago to MCPE 1.6, however ProtocolSupportPE wasn't stable at the time, so I didn't finish the upgrade

https://github.com/ProtocolSupport/ProtocolSupportBungee/tree/mcpe-1.6

**Comment by Princess-of-Klaxosaurs** [comment]
Wow that's quick :p

**Comment by Xayanix** [comment]
> Is ProtocolSupportBungee disconnecting, or is ProtocolSupport?

PSB.
Ty for quick reply.

**Comment by MrPowerGamerBR** [comment]
@Xayanix please try using the branch (compile it with gradle) I shared before... I doubt it will allow you to login (it will probably get stuck after joining the world) but it is better than nothing at the moment.

**Comment by Xayanix** [comment]
Sure, i will try to investigate this problem at night. thx

**Comment by Xayanix** [comment]
1.6 branch still throws outdated version info because 1.6.1 came out.

**Comment by Xayanix** [comment]
This should be helpful with 1.6.1 support.
https://github.com/DragonetMC/DragonProxy/pull/368

**Comment by Princess-of-Klaxosaurs** [comment]
@Xayanix  did you update it psbungee is uptodate at that branch and pspe 2

**Comment by Princess-of-Klaxosaurs** [comment]
there are no big protocol changes in 1.6.1
