### ISSUE TITLE
Breaks hybrid servers

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportBungee#70]
As you might now, many servers use a "hybrid" auth system, where Premium users keep their Mojang UUID but Cracked users can still join and play normally.
Well, a user in my server reported that they couldn't connect with a Cracked account. I've tested it and discovered PSB caused it.

Could this be patched please?

Also, i'd like to request a way to disable Authentication for PE users, maybe a boolean in a config file.

**Comment by Shevchik** [comment]
Well, this is not a normal bungee behaviour, so you are using some sort of plugin to achieve that. I need to know which plugin is that.

**Comment by Artuto** [comment]
I'm using [Bungee Premium Authenticator ](https://www.spigotmc.org/login/two-step?redirect=%2Fresources%2Fbungee-1-7-x-1-10-premium-authenticator-login-only-for-non-premium-extra-price.2750)

**Comment by Artuto** [comment]
[Proposal] I could open a PR and make it toggle-able by using a start flag.

**Comment by Shevchik** [comment]
The provided pluguin has no available source so i can't help you.

**Comment by Artuto** [comment]
I was able to fix this issue by reverting https://github.com/ProtocolSupport/ProtocolSupportBungee/commit/d07abb58b6375179a86914cdf994fd6889834bf6

**Comment by Shevchik** [comment]
By reverting rhis patch you made bungee always work in offline mode.

**Comment by Artuto** [comment]
I doubt it because if I turned off `online-mode` in config.yml users werent authenticated at all. However, reverting it allows that plugin to work. If you want I can give you a copy to test

**Comment by Artuto** [comment]
Without the plugin makes the server completely offline or online mode, which I dont want.

With that plugin Premium users get their UUID restored. Without it we would need to choose either making it premium only (which is not an option because at least half of my user-base is cracked) or having offline UUIDs which is also bad.

The plugin just pretty much let Cracked users to join and set a password.
