### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by ITZVGcGPmO** [ProtocolSupport/ProtocolSupportBungee#79]
[Travertine Apr-23-2019](https://github.com/PaperMC/Travertine/tree/29deb8df30b5b3b8721fe0321b7ec725ec40526c)

https://gist.github.com/ITZVGcGPmO/2437e7aeaca5ceaf4ace2825bf3bf93b

**Comment by Speentie8081** [comment]
[ProtocolSupportBungee for 1.14-pre5 and 1.14](https://ci.skorrloregaming.com/job/ProtocolSupportBungee-1.14/)
[commit/1d9a73e49873bb9f67ce634b919f320a0bdc7ee9](https://github.com/Speentie8081/ProtocolSupportBungee/commit/1d9a73e49873bb9f67ce634b919f320a0bdc7ee9)
