### ISSUE TITLE
Error upon joining with PE using latest travetine build.

### ISSUE THREAD

**Issue by sachk** [ProtocolSupport/ProtocolSupportBungee#80]
Log is https://pastebin.com/uGQp4A3b

From what I can see it looks like the newest commits changes in src/protocolsupport/protocol/packet/middleimpl/readable/play/v_pe/LoginPacket.java broke something in my particular setup. The player just joins then looses connection in the log on the spigot server with ProtocolSupport.

**Comment by WesleyVanNeck** [comment]
@sachk  dont use this one for pe

**Comment by sachk** [comment]
It's in the readme though. Which fork or whatever is the current one for PE?

**Comment by sachk** [comment]
I'm using waterdog now, which works. Pretty sure this is still a problem though.

**Comment by Shevchik** [comment]
The latest commit changes require you to use bungee for 1.14

**Comment by sachk** [comment]
I'm using travertine for 1.14. This happened on build 100, 98 and 92.

**Comment by Shevchik** [comment]
Current psb uses travertine build 99.
