### ISSUE TITLE
This issue Is protocolsupportbungee problem?

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupportBungee#9]
http://pastebin.com/k7xRb0zi

I use ServerView Bungeecord Plugins. But 1.5.2 Clinet is crahs. Can you Fix it if this problem is protocolsupportbungee Problem?

**Comment by Shevchik** [comment]
I can probably fix that, but that will take a lot of time

**Comment by swan201** [comment]
ok I waiting for fix this issue :)
